# Site settings
title: Finite Loop
description: "Thougts on technology"
url: "http://finiteloop.me"
author:
  name: "Kunal Limaye"
  twitter: "finiteloopme"
  url: "http://finiteloop.me"

# Plugins
whiltelist: []
gems: [jekyll-paginate, jekyll-watch]

# Build settings
baseurl: "" # Change this to your relative path (ex: /blog/), or leave just a /
source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

highlighter: rouge
markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true